### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Titoo8899** [CleanroomMC/NeverEnoughAnimation#1]
hi,

your mod work not. I have put the file in my Mods folder and have start Forge but the Game Crash with Exit-Code:1

I have the this mods in the Modsfolder

- NeverEnoughAnimation  
- MixinBooter

Please fix this Problem

**Comment by brachy84** [comment]
Send a crash log (via https://mclo.gs/). you cant find it in your `[instance]/crash-reports/` folder

**Comment by brachy84** [comment]
Fixed the problem. New version is waiting for approval on cf
