### ISSUE TITLE
Hover animation activated incorrectly

### ISSUE THREAD

**Issue by PowfuArras** [CleanroomMC/NeverEnoughAnimation#2]
The hover animation is applied to all items regardless of what slot I am hovering over. This seems to only occur in the creative mode gui

![image](https://github.com/user-attachments/assets/40de5d37-cbc9-4a24-b8d4-0d160a0bc356)

**Comment by brachy84** [comment]
Wtf. Can you reproduce it with just mixinbooter and this mod installed?

**Comment by PowfuArras** [comment]
I am able to reproduce this with as few mods installed as possible, even disabled my resource packs
![image](https://github.com/user-attachments/assets/bd9a99bf-a802-488e-af4d-215cbdd54475)

**Comment by PowfuArras** [comment]
As a temporary bandaid fix, would I be able to add the gui for the creative mode inventory to the blacklist? If so could you tell me what the gui class is, or how to find it

**Comment by brachy84** [comment]
`net.minecraft.client.gui.inventory.GuiContainerCreative`

**Comment by brachy84** [comment]
Fixed in last commit. Blame minecraft on this one
