### ISSUE TITLE
More creative inventory issues

### ISSUE THREAD

**Issue by PowfuArras** [CleanroomMC/NeverEnoughAnimation#3]
When you shift-click items between the hotbar and the creative inventory, the animation for the item moving overshoots what the location should be and it looks strange.

Another thing, when double-clicking an item in the creative inventory it wont stack all instances of that item. (i.e. 64 wool spread across 4 slots, it wont combine them into one stack upon double-click)

As before, only happens in the creative inventory.

I am able to reproduce this issue with only this mod (and mixinbooter) enabled.

This issue occurs both on the current latest release and building from source on commit 840ea51d99db1ab0fcb1c39358de7086ee37a43c.

**Comment by mczph** [comment]
![PixPin_2024-07-13_12-10-42](https://github.com/user-attachments/assets/e794e7d8-a405-48e1-b812-85e45c9feb7f)

**Comment by brachy84** [comment]
this looks funny

**Comment by brachy84** [comment]
The shift click issue has been resolved. The double click issue is a vanilla issue. Dev builds are now available in the actions tab
