### ISSUE TITLE
[Suggestion] Add animations for inventory hotbar swapping

### ISSUE THREAD

**Issue by PowfuArras** [CleanroomMC/NeverEnoughAnimation#5]
Title.

I.e. when you hover over a slot in your inventory and press one of your keybinds for your hotbar and the item travels from your hotbar to the hovered slot. (Also the inverse)

**Comment by brachy84** [comment]
Is that a vanilla feature? I never knew that existed.

**Comment by PowfuArras** [comment]
Yeah it's vanilla. "hotbar swapping" might not be the correct term. 

[This video](https://www.youtube.com/watch?v=ii5wtpukQtg) shows the mechanic I'm talking about at [0:31](https://youtu.be/ii5wtpukQtg?si=5Lx2a_HVuZEendcu&t=31). Honestly though, most of the inventory mechanics shown in that video might as well be a part of the suggestion.
